### ISSUE TITLE
Bookwyrm service doesn't start due to missing celery module

### ISSUE THREAD

**Issue by mapperfr** [YunoHost-Apps/bookwyrm_ynh#67]
Under Yunohost 12.0.6, Bookwyrm service fails. It seems to be due to a missing celery module. I did the upgrade yo YH 12 on Nov. 5th and unsuccessfully tried to restart the service today. Here's the log of bookwyrm-beat:

```
  - Nov 05 20:05:54 celery[1234]:     self.ensure_connection()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
  - Nov 05 20:05:54 celery[1234]:     self.connect()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
  - Nov 05 20:05:54 celery[1234]:     raise dj_exc_value.with_traceback(traceback) from exc_value
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
  - Nov 05 20:05:54 celery[1234]:     self.connect()
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
  - Nov 05 20:05:54 celery[1234]:     self.connection = self.get_new_connection(conn_params)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
  - Nov 05 20:05:54 celery[1234]:     return func(*args, **kwargs)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
  - Nov 05 20:05:54 celery[1234]:     connection = Database.connect(**conn_params)
  - Nov 05 20:05:54 celery[1234]:   File "/var/www/bookwyrm/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
  - Nov 05 20:05:54 celery[1234]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  - Nov 05 20:05:54 celery[1234]: django.db.utils.OperationalError: could not connect to server: Connection refused
  - Nov 05 20:05:54 celery[1234]:         Is the server running on host "localhost" (::1) and accepting
  - Nov 05 20:05:54 celery[1234]:         TCP/IP connections on port 5432?
  - Nov 05 20:05:54 celery[1234]: could not connect to server: Connection refused
  - Nov 05 20:05:54 celery[1234]:         Is the server running on host "localhost" (127.0.0.1) and accepting
  - Nov 05 20:05:54 celery[1234]:         TCP/IP connections on port 5432?
  - Nov 05 20:09:39 systemd[1]: Stopping bookwyrm-beat.service - bookwyrm celery beat process...
  - Nov 05 20:09:46 celery[1234]: celery beat v5.2.7 (dawn-chorus) is starting.
  - Nov 05 20:09:46 celery[1234]: __    -    ... __   -        _
  - Nov 05 20:09:46 celery[1234]: LocalTime -> 2024-08-14 09:17:34
  - Nov 05 20:09:46 celery[1234]: Configuration ->
  - Nov 05 20:09:46 celery[1234]:     . broker -> redis://localhost:6379/0
  - Nov 05 20:09:46 celery[1234]:     . loader -> celery.loaders.app.AppLoader
  - Nov 05 20:09:46 celery[1234]:     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
  - Nov 05 20:09:46 celery[1234]:     . logfile -> [stderr]@%INFO
  - Nov 05 20:09:46 celery[1234]:     . maxinterval -> 5.00 seconds (5s)
  - Nov 05 20:09:47 systemd[1]: bookwyrm-beat.service: Deactivated successfully.
  - Nov 05 20:09:47 systemd[1]: Stopped bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 05 20:09:47 systemd[1]: bookwyrm-beat.service: Consumed 5h 7min 28.157s CPU time.
  - -- Boot 474ec49f7064465baa590691e851f37d --
  - Nov 05 20:10:01 systemd[1]: Started bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 05 20:10:02 celery[1327]: Traceback (most recent call last):
  - Nov 05 20:10:02 celery[1327]:   File "/var/www/bookwyrm/venv/bin/celery", line 5, in <module>
  - Nov 05 20:10:02 celery[1327]:     from celery.__main__ import main
  - Nov 05 20:10:02 celery[1327]: ModuleNotFoundError: No module named 'celery'
  - Nov 05 20:10:02 systemd[1]: bookwyrm-beat.service: Main process exited, code=exited, status=1/FAILURE
  - Nov 05 20:10:02 systemd[1]: bookwyrm-beat.service: Failed with result 'exit-code'.
  - Nov 13 10:59:23 systemd[1]: Started bookwyrm-beat.service - bookwyrm celery beat process.
  - Nov 13 10:59:23 (celery)[165426]: bookwyrm-beat.service: Failed to locate executable /var/www/bookwyrm/venv/bin/celery: No such file or directory
  - Nov 13 10:59:23 (celery)[165426]: bookwyrm-beat.service: Failed at step EXEC spawning /var/www/bookwyrm/venv/bin/celery: No such file or directory
  - Nov 13 10:59:23 systemd[1]: bookwyrm-beat.service: Main process exited, code=exited, status=203/EXEC
  - Nov 13 10:59:23 systemd[1]: bookwyrm-beat.service: Failed with result 'exit-code'.
  ``` 

### Context

- Raspberry Pi 4 / Olimex A20, lime2, running Debian 12 bookworm & YunoHost 12.0.6, accessed through SSH & through the webadmin.

**Comment by mapperfr** [comment]
Follow-up: I've logged in in to the yunohost server through SSH, activated the virtual env at `/var/www/bookwyrm/venv/`, and tried to `pip install` on the missing modules. The issue seemed to go forward as I was asked to install other missing modules, and I successively installed celery, environs, requests, gunicorn, django (yeah, that seemed to be missing too...). 

It got stuck with a similar message regarding the file_resubmit module as bookwyrm-beat, bookwyrm-worker and bookwyrm-server services still fail to start. Here's the most recent log for bookwyrm-server:

```


LOGFILE: journalctl
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
Dec 06 13:55:30 gunicorn[816408]:     self.wsgi = self.app.wsgi()
Dec 06 13:55:30 gunicorn[816408]:                 ^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/gunicorn/app/base.py", line 66, in wsgi
Dec 06 13:55:30 gunicorn[816408]:     self.callable = self.load()
Dec 06 13:55:30 gunicorn[816408]:                     ^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
Dec 06 13:55:30 gunicorn[816408]:     return self.load_wsgiapp()
Dec 06 13:55:30 gunicorn[816408]:            ^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
Dec 06 13:55:30 gunicorn[816408]:     return util.import_app(self.app_uri)
Dec 06 13:55:30 gunicorn[816408]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/gunicorn/util.py", line 370, in import_app
Dec 06 13:55:30 gunicorn[816408]:     mod = importlib.import_module(module)
Dec 06 13:55:30 gunicorn[816408]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Dec 06 13:55:30 gunicorn[816408]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 06 13:55:30 gunicorn[816408]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/bookwyrm/wsgi.py", line 18, in <module>
Dec 06 13:55:30 gunicorn[816408]:     application = get_wsgi_application()
Dec 06 13:55:30 gunicorn[816408]:                   ^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
Dec 06 13:55:30 gunicorn[816408]:     django.setup(set_prefix=False)
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
Dec 06 13:55:30 gunicorn[816408]:     apps.populate(settings.INSTALLED_APPS)
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
Dec 06 13:55:30 gunicorn[816408]:     app_config = AppConfig.create(entry)
Dec 06 13:55:30 gunicorn[816408]:                  ^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/apps/config.py", line 193, in create
Dec 06 13:55:30 gunicorn[816408]:     import_module(entry)
Dec 06 13:55:30 gunicorn[816408]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Dec 06 13:55:30 gunicorn[816408]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 06 13:55:30 gunicorn[816408]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Dec 06 13:55:30 gunicorn[816408]:   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
Dec 06 13:55:30 gunicorn[816408]: ModuleNotFoundError: No module named 'file_resubmit'
Dec 06 13:55:30 gunicorn[816408]: [2024-12-06 13:55:30 +0000] [816408] [INFO] Worker exiting (pid: 816408)
Dec 06 13:55:30 gunicorn[816390]: [2024-12-06 13:55:30 +0000] [816390] [ERROR] Worker (pid:816408) exited with code 3
Dec 06 13:55:30 gunicorn[816390]: [2024-12-06 13:55:30 +0000] [816390] [ERROR] Shutting down: Master
Dec 06 13:55:30 gunicorn[816390]: [2024-12-06 13:55:30 +0000] [816390] [ERROR] Reason: Worker failed to boot.
Dec 06 13:55:30 systemd[1]: bookwyrm-server.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Dec 06 13:55:30 systemd[1]: bookwyrm-server.service: Failed with result 'exit-code'.
Dec 06 13:55:30 systemd[1]: bookwyrm-server.service: Consumed 1.637s CPU time.
```

**Comment by Thovi98** [comment]
Did you already try to force upgrade the app?

`yunohost app upgrade bookwyrm --force`

**Comment by mapperfr** [comment]
Thanks for the suggestion @Thovi98, I didn't think about this.  
I just did try it, now the services seem to be running fine and the instance looks more accessible. However, there's the following error message on the home page: 

"Server-side error  
An error has occurred; sorry!"

![screenshot_20241207_032229](https://github.com/user-attachments/assets/0308bbd6-7d78-40d3-8c24-092eb32594d2)

I can't connect or reach any other internal URL (like /preferences, or 

See the instance at https://b.falai.se.

**Comment by Thovi98** [comment]
Please share your bookwyrm services logs

**Comment by mapperfr** [comment]
Sure!

bookwyrm-server is running. Most recent log: 

```
LOGFILE: journalctl
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 519, in render
Dec 19 09:51:01 gunicorn[1959]:     return self.nodelist.render(context)
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 938, in render
Dec 19 09:51:01 gunicorn[1959]:     bit = node.render_annotated(context)
Dec 19 09:51:01 gunicorn[1959]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 905, in render_annotated
Dec 19 09:51:01 gunicorn[1959]:     return self.render(context)
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 62, in render
Dec 19 09:51:01 gunicorn[1959]:     result = block.nodelist.render(context)
Dec 19 09:51:01 gunicorn[1959]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 938, in render
Dec 19 09:51:01 gunicorn[1959]:     bit = node.render_annotated(context)
Dec 19 09:51:01 gunicorn[1959]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 905, in render_annotated
Dec 19 09:51:01 gunicorn[1959]:     return self.render(context)
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 62, in render
Dec 19 09:51:01 gunicorn[1959]:     result = block.nodelist.render(context)
Dec 19 09:51:01 gunicorn[1959]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 938, in render
Dec 19 09:51:01 gunicorn[1959]:     bit = node.render_annotated(context)
Dec 19 09:51:01 gunicorn[1959]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/template/base.py", line 905, in render_annotated
Dec 19 09:51:01 gunicorn[1959]:     return self.render(context)
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django/templatetags/cache.py", line 45, in render
Dec 19 09:51:01 gunicorn[1959]:     value = fragment_cache.get(cache_key)
Dec 19 09:51:01 gunicorn[1959]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django_redis/cache.py", line 91, in get
Dec 19 09:51:01 gunicorn[1959]:     value = self._get(key, default, version, client)
Dec 19 09:51:01 gunicorn[1959]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django_redis/cache.py", line 38, in _decorator
Dec 19 09:51:01 gunicorn[1959]:     raise e.__cause__
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/django_redis/client/default.py", line 258, in get
Dec 19 09:51:01 gunicorn[1959]:     value = client.get(key)
Dec 19 09:51:01 gunicorn[1959]:             ^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/commands/core.py", line 1790, in get
Dec 19 09:51:01 gunicorn[1959]:     return self.execute_command("GET", name)
Dec 19 09:51:01 gunicorn[1959]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
Dec 19 09:51:01 gunicorn[1959]:     conn = self.connection or pool.get_connection(command_name, **options)
Dec 19 09:51:01 gunicorn[1959]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/connection.py", line 1442, in get_connection
Dec 19 09:51:01 gunicorn[1959]:     connection.connect()
Dec 19 09:51:01 gunicorn[1959]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/connection.py", line 704, in connect
Dec 19 09:51:01 gunicorn[1959]:     raise ConnectionError(self._error_message(e))
Dec 19 09:51:01 gunicorn[1959]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

bookwyrm-beat has been failed for five days now. Most recent log:

```
LOGFILE: journalctl
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,936: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,937: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,938: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,938: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,938: WARNING/MainProcess] ^
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,938: WARNING/MainProcess]   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 406, in ensure_connection
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,939: WARNING/MainProcess]
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,939: WARNING/MainProcess] self._ensure_connection(*args, **kwargs)
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,939: WARNING/MainProcess]   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 458, in _ensure_connection
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,939: WARNING/MainProcess]
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,940: WARNING/MainProcess] with ctx():
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,940: WARNING/MainProcess]   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,940: WARNING/MainProcess]
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,940: WARNING/MainProcess] self.gen.throw(typ, value, traceback)
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,941: WARNING/MainProcess]   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,941: WARNING/MainProcess]
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,941: WARNING/MainProcess] raise ConnectionError(str(exc)) from exc
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,941: WARNING/MainProcess] kombu.exceptions
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,942: WARNING/MainProcess] .
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,942: WARNING/MainProcess] OperationalError
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,942: WARNING/MainProcess] :
Dec 14 19:09:30 celery[1597]: [2024-12-14 19:09:30,942: WARNING/MainProcess] Error 111 connecting to localhost:6379. Connection refused.
Dec 14 19:09:31 celery[1597]: celery beat v5.2.7 (dawn-chorus) is starting.
Dec 14 19:09:31 celery[1597]: __    -    ... __   -        _
Dec 14 19:09:31 celery[1597]: LocalTime -> 2024-12-14 18:20:09
Dec 14 19:09:31 celery[1597]: Configuration ->
Dec 14 19:09:31 celery[1597]:     . broker -> redis://localhost:6379/0
Dec 14 19:09:31 celery[1597]:     . loader -> celery.loaders.app.AppLoader
Dec 14 19:09:31 celery[1597]:     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
Dec 14 19:09:31 celery[1597]:     . logfile -> [stderr]@%INFO
Dec 14 19:09:31 celery[1597]:     . maxinterval -> 5.00 seconds (5s)
Dec 14 19:09:31 systemd[1]: bookwyrm-beat.service: Main process exited, code=exited, status=1/FAILURE
Dec 14 19:09:31 systemd[1]: bookwyrm-beat.service: Failed with result 'exit-code'.
Dec 14 19:09:31 systemd[1]: bookwyrm-beat.service: Consumed 9.387s CPU time.
```

bookwyrm-worker has been inactive for 5 days too. Log: 
```
LOGFILE: journalctl
Dec 14 19:09:31 celery[1603]:               ^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/transport/redis.py", line 744, in __init__
Dec 14 19:09:31 celery[1603]:     self.client.ping()
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/commands/core.py", line 1194, in ping
Dec 14 19:09:31 celery[1603]:     return self.execute_command("PING", **kwargs)
Dec 14 19:09:31 celery[1603]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
Dec 14 19:09:31 celery[1603]:     conn = self.connection or pool.get_connection(command_name, **options)
Dec 14 19:09:31 celery[1603]:                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/connection.py", line 1442, in get_connection
Dec 14 19:09:31 celery[1603]:     connection.connect()
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/redis/connection.py", line 704, in connect
Dec 14 19:09:31 celery[1603]:     raise ConnectionError(self._error_message(e))
Dec 14 19:09:31 celery[1603]: redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
Dec 14 19:09:31 celery[1603]: The above exception was the direct cause of the following exception:
Dec 14 19:09:31 celery[1603]: Traceback (most recent call last):
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/worker.py", line 203, in start
Dec 14 19:09:31 celery[1603]:     self.blueprint.start(self)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
Dec 14 19:09:31 celery[1603]:     step.start(parent)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 365, in start
Dec 14 19:09:31 celery[1603]:     return self.obj.start()
Dec 14 19:09:31 celery[1603]:            ^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 332, in start
Dec 14 19:09:31 celery[1603]:     blueprint.start(self)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
Dec 14 19:09:31 celery[1603]:     step.start(parent)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/consumer/connection.py", line 21, in start
Dec 14 19:09:31 celery[1603]:     c.connection = c.connect()
Dec 14 19:09:31 celery[1603]:                    ^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 428, in connect
Dec 14 19:09:31 celery[1603]:     conn = self.connection_for_read(heartbeat=self.amqheartbeat)
Dec 14 19:09:31 celery[1603]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 434, in connection_for_read
Dec 14 19:09:31 celery[1603]:     return self.ensure_connected(
Dec 14 19:09:31 celery[1603]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 460, in ensure_connected
Dec 14 19:09:31 celery[1603]:     conn = conn.ensure_connection(
Dec 14 19:09:31 celery[1603]:            ^^^^^^^^^^^^^^^^^^^^^^^
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 406, in ensure_connection
Dec 14 19:09:31 celery[1603]:     self._ensure_connection(*args, **kwargs)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 458, in _ensure_connection
Dec 14 19:09:31 celery[1603]:     with ctx():
Dec 14 19:09:31 celery[1603]:   File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
Dec 14 19:09:31 celery[1603]:     self.gen.throw(typ, value, traceback)
Dec 14 19:09:31 celery[1603]:   File "/var/www/bookwyrm/venv/lib/python3.11/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
Dec 14 19:09:31 celery[1603]:     raise ConnectionError(str(exc)) from exc
Dec 14 19:09:31 celery[1603]: kombu.exceptions.OperationalError: Error 111 connecting to localhost:6379. Connection refused.
Dec 14 19:09:33 systemd[1]: bookwyrm-worker.service: Deactivated successfully.
Dec 14 19:09:33 systemd[1]: bookwyrm-worker.service: Consumed 10.590s CPU time.
```

**Comment by mapperfr** [comment]
Closing this issue as a recent update fixed it. No idea what happened though, and I lost all the images I uploaded in the process.
